version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: banco_postgres
    environment:
      POSTGRES_DB: bancadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: banco_rabbitmq
    ports:
      - "5672:5672"   # para la aplicación
      - "15672:15672" # para acceder al panel de administración
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

volumes:
  postgres_data:
